# Generated by Django 5.2.9 on 2026-01-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='property',
            name='legal_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Razão Social'),
        ),
    ]
