# Generated by Django 5.2.9 on 2026-01-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_facebook_property_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='tiktok',
            field=models.CharField(blank=True, max_length=100, verbose_name='TikTok'),
        ),
        migrations.AddField(
            model_name='property',
            name='youtube',
            field=models.CharField(blank=True, max_length=100, verbose_name='YouTube'),
        ),
    ]
