# Generated by Django 5.2.9 on 2026-01-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_tiktok_property_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='custom_domain',
            field=models.CharField(blank=True, max_length=200, verbose_name='Domínio Personalizado'),
        ),
        migrations.AddField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug (URL)'),
        ),
    ]
